//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{ Deserialize, Serialize };

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "reagents")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub chem_lab: String,
    #[sea_orm(column_type = "Text")]
    pub chem_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub chem_cas: Option<String>,
    pub reagent_num: i64,
    pub batch_num: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub existing_stock: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub producer: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub place: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub cabinet: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub msds_url: Option<String>,
    #[sea_orm(ignore, column_type = "custom(\"DATETIME\")", select_as = "text", nullable)]
    pub create_at: Option<String>,
    #[sea_orm(ignore, column_type = "custom(\"DATETIME\")", select_as = "text", nullable)]
    pub update_at: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub other: Option<String>,
    pub status: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
